using Shinobytes.Ravenfall.Data.Entities;
using System;

namespace Shinobytes.Ravenfall.DataModels
{
    public class NPC : Entity<NPC>
    {
        private Guid _Id; public Guid Id { get => _Id; set => Set(ref _Id, value); }
        private string _Name; public string Name { get => _Name; set => Set(ref _Name, value); }
        private int _Attack; public int Attack { get => _Attack; set => Set(ref _Attack, value); }
        private int _Defense; public int Defense { get => _Defense; set => Set(ref _Defense, value); }
        private int _Health; public int Health { get => _Health; set => Set(ref _Health, value); }
        private int _WeaponAim; public int WeaponAim { get => _WeaponAim; set => Set(ref _WeaponAim, value); }
        private int _WeaponPower; public int WeaponPower { get => _WeaponPower; set => Set(ref _WeaponPower, value); }
        private int _ArmorPower; public int ArmorPower { get => _ArmorPower; set => Set(ref _ArmorPower, value); }
        private bool _IsStatsAutoGenerated; public bool IsStatsAutoGenerated { get => _IsStatsAutoGenerated; set => Set(ref _IsStatsAutoGenerated, value); }
        private bool _IsAttackable; public bool IsAttackable { get => _IsAttackable; set => Set(ref _IsAttackable, value); }
        private bool _IsAggressive; public bool IsAggressive { get => _IsAggressive; set => Set(ref _IsAggressive, value); }
        private bool _IsRaidBoss; public bool IsRaidBoss { get => _IsRaidBoss; set => Set(ref _IsRaidBoss, value); }
        private bool _IsDungeonBoss; public bool IsDungeonBoss { get => _IsDungeonBoss; set => Set(ref _IsDungeonBoss, value); }
        private string _Prefab; public string Prefab { get => _Prefab; set => Set(ref _Prefab, value); }
    }
}